### ISSUE TITLE
createVMfromdisk

### ISSUE THREAD

**Issue by tiankangbo2019** [zrax/libvbox#1]
hello, this project is great, And I tried to test it. But A mistake has occurred when I tried to use this project to create VM.

example:
```c++
void MyVbox::createVMfromdisk()
{
auto vboxClient = VBox::virtualBoxClient();
auto vbox = vboxClient->virtualBox();
auto mediumhdd = VBox::IMedium();
auto session =vboxClient->session();
//createMachine
auto machine = vbox->createMachine(u"", u"my", vectorstd::u16string(0), u"RedHat_64", u"");

machine->set_CPUCount(1);
machine->set_OSTypeId(u"RedHat_64");
machine->set_memorySize(2048);

//register
vbox->registerMachine(machine);

machine->lockMachine(session, VBox::LockType::Write);

auto disk = vbox->openMedium(u"/root/centos.qcow2", VBox::DeviceType::HardDisk, VBox::AccessMode::ReadWrite, true);
if(disk){
    qDebug()<<"disk name:"<<disk->name();
    qDebug()<<"size:"<<disk->size();
    qDebug()<<"id:"<<disk->id();
}
auto ctl = machine->addStorageController(u"SATA", VBox::StorageBus::SATA);
qDebug()<<"ctl name:"<<ctl->name();

qDebug()<<"####4";
machine->attachDevice(u"SATA Controller", 0, ctl, VBox::DeviceType::HardDisk, disk);

machine->setStorageControllerBootable(u"SATA Controller", true);
qDebug()<<"11111";

machine->setBootOrder(0, VBox::DeviceType::HardDisk);
qDebug()<<"####5";

session->unlockMachine();

qDebug()<<"hello!!";
}
```

######################################################
1. When the program runs to "addStorage Controller", an error occurs.
2. u"/root/centos.qcow2" ， Disk with system installed
######################################################
ifc: 0x9c1ad0
iid: 0x7f710dc5aa10
disk name: "centos.qcow2"
size: 21478375424
id: "b773ded4-328e-4352-b363-1e44063e42d6"
terminate called after throwing an instance of 'VBox::EInvalidVMState'
what(): COM Error 0x80bb0002: E_INVALID_VM_STATE
15:37:17: 程序异常结束。
######################################################

**Comment by tiankangbo2019** [comment]
and ,How to create a virtual machine from ISO or disk？Can you give a program case?

**Comment by zrax** [comment]
According to the VirtualBox SDK manual, you need to obtain a mutable IMachine from the ISession after locking it:

```c++
machine->lockMachine(session, VBox::LockType::Write);
auto mutableMachine = session->machine();

/* ... */

auto ctl = mutableMachine->addStorageController(u"SATA", VBox::StorageBus::SATA);
```

This will allow you to set properties and add devices to the machine.

On an unrelated note, you can get more details on exceptions (beyond just "EInvalidVMState") by examining the exception's `text()` method...  For example:
```c++
try {
    // Some libvbox stuff
} catch (const VBox::COMError &err) {
    auto errorInfo = VBox::currentError();
    auto vboxError = errorInfo->QueryInterface<VBox::IVirtualBoxErrorInfo>();
    if (vboxError) {
        qDebug() << err.what();
        while (vboxError) {
            qDebug() << "VBox error: " << VBox::utf16ToUtf8(vboxError->text());
            vboxError = vboxError->next();
        }
    }
}
```

**Comment by zrax** [comment]
As for setting up a VM from an ISO, I expect you'll want to look at `IUnattended`.  It's not something I've tried though, so I can't offer much advice aside from reading the manual and trying it out.

**Comment by tiankangbo2019** [comment]
The program is working now. Thank you very much.
