### ISSUE TITLE
Whether the project can run in MinGW environment instead of MSVC environment

### ISSUE THREAD

**Issue by tiankangbo2019** [zrax/libvbox#2]
Hi，Michael Hansen. Whether the project can run in MinGW environment instead of MSVC environment?  And How to modify the CMakeLists. TXT file can do that？

**Comment by zrax** [comment]
In theory, I suppose it could work...  However, it looks like the generated VirtualBox headers included in the VirtualBox SDK currently require a newer version of some platform headers than what MinGW currently provides.  You'd need to either get a fix/update from MinGW, or rebuild your VirtualBox SDK headers with an older MSIDL compiler.
