### ISSUE TITLE
full clone VM

### ISSUE THREAD

**Issue by tiankangbo2019** [zrax/libvbox#3]
Hi，Michael Hansen. Have you ever tried to clone virtual machines using cloneTo and cloneToBase functions?  What functions should be executed before using cloneTo and cloneToBase functions?  And can you give me some guidance on how to code it?

**Comment by tiankangbo2019** [comment]
and  Here is my test code.

/*

void MyVbox::cloneFullVM()
{
    try{
        auto vboxClient = VBox::virtualBoxClient();
        auto vbox = vboxClient->virtualBox();
//        auto session = vboxClient->session();
        auto machine = vbox->findMachine(u"centos");

        auto targetmachine = vbox->createMachine(u"", u"clonetest", vector<std::u16string>(0), u"Ubuntu_64", u"");
        if(targetmachine){
            qDebug()<<"create machine ok!";
        }
        //register
        vbox->registerMachine(targetmachine);

        std::vector<VBox::CloneOptions> options;
        options.push_back(VBox::CloneOptions::KeepNATMACs);

        auto snap = machine->cloneTo(targetmachine, VBox::CloneMode::MachineState, options);
        snap->waitForCompletion(-1);


     } catch (const VBox::COMError &err) {

        auto errorInfo = VBox::currentError();
        auto vboxError = errorInfo->QueryInterface<VBox::IVirtualBoxErrorInfo>();
        if (vboxError) {
         qDebug()<<"err :"<<err.what();
         while (vboxError) {
                qDebug()<<vboxError->text();
                vboxError = vboxError->next();
            }
        }
     }
}

*/

################################################

When the program runs to "snap - > waitForCompletion (- 1);", the code clones the complete disk of the virtual machine, but the VBox crashes.   Are there steps missing in the code?

**Comment by tiankangbo2019** [comment]
and Here is my test code.

/*

void MyVbox::cloneFullVM()
{
try{
auto vboxClient = VBox::virtualBoxClient();
auto vbox = vboxClient->virtualBox();
// auto session = vboxClient->session();
auto machine = vbox->findMachine(u"centos");

    auto targetmachine = vbox->createMachine(u"", u"clonetest", vector<std::u16string>(0), u"RedHat_64", u"");
    if(targetmachine){
        qDebug()<<"create machine ok!";
    }
    //register
    vbox->registerMachine(targetmachine);

    std::vector<VBox::CloneOptions> options;
    options.push_back(VBox::CloneOptions::KeepNATMACs);

    auto snap = machine->cloneTo(targetmachine, VBox::CloneMode::MachineState, options);
    snap->waitForCompletion(-1);


 } catch (const VBox::COMError &err) {

    auto errorInfo = VBox::currentError();
    auto vboxError = errorInfo->QueryInterface<VBox::IVirtualBoxErrorInfo>();
    if (vboxError) {
     qDebug()<<"err :"<<err.what();
     while (vboxError) {
            qDebug()<<vboxError->text();
            vboxError = vboxError->next();
        }
    }
 }
}

*/

################################################

When the program runs to "snap - > waitForCompletion (- 1);", the code clones the complete disk of the virtual machine, but the VBox crashes. Are there steps missing in the code?

**Comment by tiankangbo2019** [comment]
Hi，Michael Hansen. Have you ever tried to clone virtual machines using cloneTo and cloneToBase functions? What functions should be executed before using cloneTo and cloneToBase functions? And can you give me some guidance on how to code it?

and Here is my test code.

```c++
void MyVbox::cloneFullVM()
{
    try{
        auto vboxClient = VBox::virtualBoxClient();
        auto vbox = vboxClient->virtualBox();
        // auto session = vboxClient->session();
        auto machine = vbox->findMachine(u"centos");
        auto targetmachine = vbox->createMachine(u"", u"clonetest", vectorstd::u16string(0), u"RedHat_64", u"");
        if(targetmachine){
            qDebug()<<"create machine ok!";
        }
        //register
        vbox->registerMachine(targetmachine);
        std::vector<VBox::CloneOptions> options;
        options.push_back(VBox::CloneOptions::KeepNATMACs);
        auto snap = machine->cloneTo(targetmachine, VBox::CloneMode::MachineState, options);
        snap->waitForCompletion(-1);
    } catch (const VBox::COMError &err) {
        auto errorInfo = VBox::currentError();
        auto vboxError = errorInfo->QueryInterfaceVBox::IVirtualBoxErrorInfo();
        if (vboxError) {
            qDebug()<<"err :"<<err.what();
            while (vboxError) {
                qDebug()<text();
                vboxError = vboxError->next();
            }
        }
    }
}
```

################################################

When the program runs to "snap - > waitForCompletion (- 1);", the code clones the complete disk of the virtual machine, but the VBox crashes. Are there steps missing in the code?

**Comment by zrax** [comment]
What do you mean by "the VBox crashes"?  Does your program crash, or does it complete successfully but creates a machine that crashes when started?

I did a quick test of something equivalent, and it looks like it cloned successfully, but did not actually make a copy the disk image(s).  The manual implies that it should, so this may be a VirtualBox issue...

**Comment by tiankangbo2019** [comment]
Oh, that's an early problem. And now,  my program can run successfully and clone a VM successfully in Linux environment, But in Windows environment,  The program ends abnormally when the cloneTo function is executed. Here is my code.
############################################
```c++
void MyVbox::cloneFullVM()
{
    try{
        auto vboxClient = VBox::virtualBoxClient();
        auto vbox = vboxClient->virtualBox();
        auto machine = vbox->findMachine(u"centos");
        std::vector<std::u16string> group;
        std::u16string group_id(u"");
        group.push_back(group_id);
        std::u16string setfile(u"");
        std::u16string flag(u"");

        auto targetmachine = vbox->createMachine(setfile, u"clonetest", group,
                                                 machine->OSTypeId(), flag);
        if(targetmachine){
            targetmachine->saveSettings();
            qDebug()<<"create machine ok!";
        }
        std::vector<VBox::CloneOptions> options;
        options.push_back(VBox::CloneOptions::KeepNATMACs);
        auto snap = machine->cloneTo(targetmachine, VBox::CloneMode::MachineState, options);

        while(!snap->completed()){
            qDebug()<<"percent-->"<<snap->percent();
        }
        vbox->registerMachine(targetmachine);

     } catch (const VBox::COMError &err) {
        auto errorInfo = VBox::currentError();
        auto vboxError = errorInfo->QueryInterface<VBox::IVirtualBoxErrorInfo>();
        if (vboxError) {
         qDebug()<<"err :"<<err.what();
         while (vboxError) {
                auto mes = vboxError->text();
                for (auto c : mes){
                    printf("%c", c);
                }
                printf("\n");
                vboxError = vboxError->next();
            }
        }
     }
}
```
############################################

But my VirtualBox software is no problem. It can clone virtual machines correctly.

And Thank you very much for your reply！

**Comment by hackflame** [comment]
![image](https://github.com/zrax/libvbox/assets/6028830/3259f074-80fb-43cc-a1f9-4e79fc915fad)

auto vboxClient = VBox::virtualBoxClient();
	printf("vboxClient = %p\r\n", vboxClient);
	auto vbox = vboxClient->virtualBox();
	auto session = vboxClient->session();
	
	printf("vbox = %p\r\n", vbox);
	printf("session = %p\r\n", session);
	try {
		auto machine = vbox->findMachine(u"win7");
	}
	catch (const VBox::COMError &err) {
		auto errorInfo = VBox::currentError();
		// Display error information...
		printf("machines error\r\n");
	}

**Comment by hackflame** [comment]
sdk 7.0.8
