### ISSUE TITLE
machines return empty & findMachine crashed

### ISSUE THREAD

**Issue by hyy829119** [zrax/libvbox#5]
**OS Version:Ubuntu 20.04.5 LTS
VirtualBox Version: 6.1.36**
![image](https://user-images.githubusercontent.com/8023711/196590666-30c325d5-3243-4e73-a6f2-a40a6554d3be.png)
![image](https://user-images.githubusercontent.com/8023711/196590763-8b00888b-cb1b-47b5-b497-2b5ce6f7ddf0.png)
![image](https://user-images.githubusercontent.com/8023711/196590868-a10c74c0-ca75-434b-9613-a491dd9348e1.png)
![image](https://user-images.githubusercontent.com/8023711/196590906-faaa9262-e0d8-4b0c-9724-77cf909ec209.png)
![image](https://user-images.githubusercontent.com/8023711/196591136-241c87fd-4907-43ee-abac-bd2cef7f1c65.png)
![image](https://user-images.githubusercontent.com/8023711/196591198-fc3343bc-41ce-43ed-8206-01593f8274c6.png)
![image](https://user-images.githubusercontent.com/8023711/196591647-26ebf90f-0934-47e6-aa1a-9ddc99dd9c03.png)

Project Based on Qt 6.0  & C++11
After compiling the so file according to the documentation, I then introduced the so into Qt, and then ran the code. Although the running code has no exception and can be started normally, the machines function returns empty, and the findMachine function is directly abnormal. The exception is as follows:

![image](https://user-images.githubusercontent.com/8023711/196591956-68f33f47-fa70-4ee0-a56e-690e0d408e33.png)

This exception directly causes the program to crash.
So I expect to know which version of VirtualBox should be based on the packaging, and the type of OS system

Thanks again, looking forward to reply

**Comment by zrax** [comment]
libvbox translates COM errors to C++ exceptions (see https://github.com/zrax/libvbox/blob/master/README.md#error-handling for details).  That means you'll need to catch the error rather than just testing for null after calling something like `findMachine()`:

```c++
#include <QCoreApplication>
#include <QDebug>
#include <libvbox.h>

int main(int argc, char *argv[])
{
    QCoreApplication app(argc, argv);

    auto vboxClient = VBox::virtualBoxClient();
    auto vbox = vboxClient->virtualBox();

    auto machines = vbox->machines();
    for (const auto &machine : machines)
        qDebug() << VBox::utf16ToUtf8(machine->name()).c_str();

    auto session = vboxClient->session();
    try {
        auto machine = vbox->findMachine(u"Windows");
        // do something with machine...
    } catch (const VBox::COMError &err) {
        qDebug() << "Could not get machine \"Windows\": " << err.what();
    }

    return 0;
}
```

If the machines list is coming up empty, perhaps the VirtualBox COM server isn't finding the machines you expect it to...  Is it maybe running as a different user?

**Comment by hyy829119** [comment]
Thank you for your patience to answer, the problem has been solved, because the project is started with sudo, but the VirtualBox software is started with normal user rights, so it can be confirmed that the machines function returns empty due to different users

Also, I expect that in the README.md file, it states that the project and virtualbox need to be started as the same user. Avoid making the same mistake as me. It's up to you!

good wishes again
